sudo: 'required'
language: java
jdk:
  - openjdk11
services:
  - docker
addons:
  sonarcloud:
    organization: "famaridon-github"
    token:
      secure: $SONAR_TOKEN

git:
  depth: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - ./.travis/setup.sh

script:
  - echo "export WAIT_DOCKER=30" > .travis/test-configuration.sh
  - ./.travis/build.sh

notifications:
  email:
    on_failure: always
    on_success: change

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file:
    - './redmine-ng-web/target/redmine-ng-api.war'
    - './target/docker-compose.tar.gz'
  skip_cleanup: true
  on:
    branch : master
    tags: true