language: java
jdk:
  - oraclejdk8

before_install:
  - wget http://download.jboss.org/wildfly/11.0.0.Final/wildfly-11.0.0.Final.zip
  - sudo unzip wildfly-11.0.0.Final.zip -d $JBOSS_HOME
  - sudo mv $JBOSS_HOME/wildfly-11.0.0.Final/* $JBOSS_HOME
  - sudo cp standalone.xml $JBOSS_HOME/standalone/configuration/standalone.xml
  - sudo chown -R $USER:$USER $JBOSS_HOME
  - cat $JBOSS_HOME/standalone/configuration/standalone.xml

install: # the build step
   - mvn clean install -B -V

script:

#before_deploy:
#  - ssh-keyscan -p $DEPLOY_PORT $DEPLOY_HOST >> ~/.ssh/known_hosts
#  - openssl aes-256-cbc -K $encrypted_041de9b33623_key -iv $encrypted_041de9b33623_iv -in ssh_key.enc -out /tmp/ssh_key -d
#  - eval "$(ssh-agent -s)"
#  - chmod 600 /tmp/ssh_key
#  - ssh-add /tmp/ssh_key
#
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: rsync -r -v -e "ssh -p $DEPLOY_PORT -i /tmp/ssh_key" $TRAVIS_BUILD_DIR/dist/* $DEPLOY_LOGIN@$DEPLOY_HOST:$DEPLOY_FOLDER
#  on:
#    branch: develop

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
