sudo: 'required'
language: java
jdk:
  - openjdk8
services:
  - docker
addons:
  sonarcloud:
    organization: "famaridon-github"
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
    - $HOME/.m2

before_install:
  - ./.travis/setup.sh

script:
  - echo "export WAIT_DOCKER=30" > .travis/test-configuration.sh

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: always
    on_success: change

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: '/redmine-ng-web/target/redmine-ng-api.war'
  skip_cleanup: true
  on:
    branch : master
    tags: true