sudo: 'required'
language: java
jdk:
  - openjdk8
services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - ./.travis/main.sh


install: # the build step
  - mvn clean install -B -V

script:
  - docker version
  - docker-compose version
  - touch .travis/test-configuration.sh
  - ./.travis/test.sh

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: always
    on_success: change
