language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - wget --quiet --no-clobber -P $JBOSS_HOME http://download.jboss.org/wildfly/14.0.1.Final/wildfly-14.0.1.Final.zip
  - sudo unzip -q $JBOSS_HOME/wildfly-14.0.1.Final.zip -d $JBOSS_HOME
  - sudo mv -f $JBOSS_HOME/wildfly-14.0.1.Final/* $JBOSS_HOME
  - sudo cp standalone.xml $JBOSS_HOME/standalone/configuration/standalone.xml
  - sudo chown -R $USER:$USER $JBOSS_HOME

install: # the build step
   - mvn clean install -B -V

script:
   - mvn -P with-test-env test

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
