language: java
jdk:
  - openjdk8
services:
  - docker


cache:
  directories:
    - $HOME/.m2

install: # the build step
  - mvn clean install -B -V

script:
  - touch test-configuration.sh
  - ./test.sh

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: always
    on_success: change
