version: '3'
services:
  database:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: redminengapi
  api:
    build: .
    ports:
      - 8080:8080
      - 9990:9990
      - 5000:5000
    volumes:
      - ./configuration:/opt/wildfly/configuration
      - ./deployement:/opt/wildfly/deployment
