version: '3'
services:
  database:
    image: mysql:5.7
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_USER: redmine-ng
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: redminengapi
  api:
    build: ./api
    environment:
      REDMINE_NG_API_PROFILE: "prod"
    volumes:
      - ./api/configuration:/opt/wildfly/configuration
      - ./api/staging:/opt/wildfly/staging
  front:
    image: nginx:1.15-alpine
    volumes:
      - ./front/www:/opt/www
      - ./front/nginx/conf.d:/etc/nginx/conf.d/
  proxy:
    image: nginx:1.15-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx/conf.d:/etc/nginx/conf.d/