version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - 3406:3306
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_USER: redmine-ng
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: redminengapi
  api:
    build: ./api
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
      - 5000:5000
      - 8860:8860
    environment:
      REDMINE_NG_API_PROFILE: "dev"
      JPROFILER: "true"
      JACOCOC: "true"
    volumes:
      - ./api/configuration:/opt/wildfly/configuration
      - ./api/staging:/opt/wildfly/staging
      - ./api/deployments:/opt/wildfly/standalone/deployments

